# Generated by Django 3.2.6 on 2021-08-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('turma', models.CharField(max_length=60)),
                ('idade', models.IntegerField(max_length=5)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('senhaCriptografada', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Alunos',
                'ordering': ('nome',),
            },
        ),
    ]
