# Generated by Django 3.2.6 on 2021-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20210928_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAluno', models.IntegerField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('entregue', models.BooleanField()),
                ('link', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Atividade',
                'ordering': ('descricao',),
            },
        ),
    ]
