# Generated by Django 3.2.6 on 2021-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='idAluno',
        ),
        migrations.AddField(
            model_name='atividade',
            name='cpfAluno',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
