# Generated by Django 3.2.6 on 2021-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_auto_20210928_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='link',
            field=models.FileField(upload_to='static/pdf/'),
        ),
    ]
