# Generated by Django 3.2.6 on 2021-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_atividade_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='picture',
            field=models.FileField(blank=True, upload_to='static/picture/'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='link',
            field=models.FileField(blank=True, upload_to='static/pdf/'),
        ),
    ]
