# Generated by Django 3.2.6 on 2021-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_auto_20210928_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to='static/turmas/')),
            ],
            options={
                'db_table': 'Turma',
                'ordering': ('nome',),
            },
        ),
    ]
